@startuml
:Пользователь передвигает корабль клавишами WASD или стрелками;
if (В направлении движения конец поля?) is (да) then
  :корабль не сдвигается с места;
else
  :на экране отображается передвижение корабля;
endif
:Игровой процесс продолжается;
@enduml
