@startuml
:Пользователь нажимает клавишу "Esc";
:Приложение отображает окно для ввода имени пользователя;
:Пользователь вводит имя;
:Приложение записывает результат и отображает главное меню;
@enduml
