@startuml
:Пользователь нажимает клавишу "Esc";
:Приложение отображает окно с предложением продолжить игру или выйти в меню;
if (Пользователь выбирает выйти в меню?) is (да) then
  :Приложение перекидывает пользователя в главное меню;
else
  :Возобнавляется игровой процесс;
endif
@enduml
