@startuml
:Корабль касается предмета;
if (Предмет является опасным?) is (да) then
  :Корабль разбивается, игра заканчивается;
else
  if (Предмет является бонусом?) is (да) then
    :Корабль получает соответствующий бонус, на экране отображается таймер;
  else
    :Счет пользователя увеличивается;
  endif
  :Предмет пропадает с поля;
  :Игровой процесс продолжается;
endif
@enduml
