@startuml
:Корабль касается предмета;
if (Предмет является опасным?) is (да) then
  if (У корабля больше 1 жизни?) is (да) then
    :У корабля отнимается 1 жизнь;
    :Предмет пропадает с поля;
    :Игровой процесс продолжается;
  else
    :Игра завершается;
  endif
else
  if (Предмет является щитом?) is (да) then
    :Корабль получает соответствующий бонус, на экране отображается таймер;
  else
    :У корабля прибавляется 1 жизнь;
  endif
  :Предмет пропадает с поля;
  :Игровой процесс продолжается;
endif
@enduml
