@startuml
:Пользователь завершает игру;
:Приложение отображает окно с предложением сохранить игру;
if (Пользователь соглашается сохранить игру?) is (да) then
  :Приложение отображает окно для ввода имени;
  :Пользователя вводит имя;
  if (Счет пользователя является рекордом?) is (да) then
    :Приложение сохраняет результат в таблице лидеров;
  else
  endif
else
endif
  :Пользователь возвращается в главное меню;
@enduml
