@startuml
:Пользователь нажимает кнопку "Рекорды";
:Приложение отображает таблицу с результатами прошедших игр;
:Пользователь просматривает таблицу;
:Пользователь нажимает клавишу  ESC;
:Приложение отображает главное меню;
@enduml
