@startuml
:Пользователь завершает игру;
:Приложение отображает окно для ввода имени;
:Пользователя вводит имя;
:Приложение сохраняет результат в таблице лидеров;
:Пользователь возвращается в главное меню;
@enduml
