@startuml
:Пользователь нажимает кнопку "Помощь";
:Приложение отображает информацию об игре (правила, управление);
:Пользователь просматривает информацию;
:Пользователь нажимает клавишу  ESC;
:Приложение отображает главное меню;
@enduml
